### ISSUE TITLE
I'm a green hand and don't have how to use keil files, do I need to add them to keil's project?

### ISSUE THREAD

**Issue by Bacholer** [viteo/STM32-BluePill-RNDIS#1]

**Comment by viteo** [comment]
That's a CubeIDE project. Either use CubeIDE or look for a way to import source files to Keil.

**Comment by Bacholer** [comment]
I have been trying to use STM32CubeIDE to complete a project, but since you did not include the contents of lwip, I encountered an error when trying to add it myself. Even after adding the path, the error still persists. Can you provide a complete project for me?

**Comment by viteo** [comment]
LwIP is included as submodule
```
git submodule init
git submodule update
```

**Comment by Bacholer** [comment]
really really thanks！
